repos:
-   repo: local
    hooks:
    -   id: ruff
        name: ruff linting
        entry: bash -c "ruff check ."
        language: system
        pass_filenames: false
        always_run: true
    -   id: mypy
        name: mypy type checking
        entry: bash -c "mypy --ignore-missing-imports --exclude tests --exclude venv --exclude __pycache__ --exclude node_modules ."
        language: system
        pass_filenames: false
        always_run: true
    -   id: pytest-coverage
        name: check code coverage
        entry: bash -c "export PYTHONPATH=$PYTHONPATH:. && pytest --cov=. --cov-fail-under=99 tests/"
        language: system
        pass_filenames: false
        always_run: true
